BF: (re)raise the exception always unless returning (#14756)
otherwise leads atm to masking of this error while testing on i386
and then failling since

UnboundLocalError: local variable unser referenced before assignment

More detail: https://buildd.debian.org/status/fetch.php?pkg=pandas&arch=i386&ver=0.19.1-1&stamp=1479504883